

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KETAN1
 */
public class InsertRawMaterial extends javax.swing.JFrame {

    /**
     * Creates new form InsertRawMaterial
     */
    public InsertRawMaterial() {
        initComponents();
        //jSpinner1.setEditor(new JSpinner.DateEditor(jSpinner1, "yyyy-mm-dd"));
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CRESCENT STEEL INDUSTRIES PVT. LTD.");
        setBackground(new java.awt.Color(153, 204, 255));
        setForeground(new java.awt.Color(153, 204, 255));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(255, 153, 255));
        label1.setFont(new java.awt.Font("AR CENA", 1, 36)); // NOI18N
        label1.setText("CRESCENT  STEEL  INDUSTRIES  PVT.  LTD.");

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Iron Ore");

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setText("Anthracite");

        jLabel3.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3.setText("Chromium");

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setText("Nickel");
        jLabel4.setToolTipText("");

        jTextField1.setText("00");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jTextField2.setText("00");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jTextField3.setText("00");
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jTextField4.setText("00");
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jButton1.setText("SUBMIT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel5.setText("Order no.");

        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jLabel6.setText("Supplier ID");

        jLabel7.setText("Status");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Delivered");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Undelivered");

        jLabel8.setText("Date of Order");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1415090893340L), null, null, java.util.Calendar.DAY_OF_MONTH));

        jLabel9.setText("Amount Due");

        jLabel10.setText("Ton");

        jLabel11.setText("Ton");

        jLabel12.setText("Quintal");

        jLabel13.setText("Quintal");

        jLabel14.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("INSERT OR UPDATE RAW MATERIAL ENTRY");

        jTextField8.setEditable(false);
        jTextField8.setText("00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel14))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel7)
                .addGap(54, 54, 54)
                .addComponent(jRadioButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jRadioButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel14)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jRadioButton1)))
                .addGap(7, 7, 7)
                .addComponent(jRadioButton2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    float total=0;
    int qty1=0;
    int qty2=0;
    int qty3=0;
    int qty4=0;
    int flag = 0;
    
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(!jButton1.isEnabled())
            return;
        
        try{ 
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con1=DriverManager.getConnection ("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","iit");
        
        int orderno = Integer.parseInt(jTextField5.getText());
        int supplierid = Integer.parseInt(jTextField6.getText());
        String s = "Undelivered";
        if(jRadioButton1.isSelected()){
           s = "Delivered";
        }
       
        
       Statement st=con1.createStatement();
       ResultSet rd=st.executeQuery("select id from supplier");
       
       Statement stmt1=con1.createStatement();
       ResultSet rs1=stmt1.executeQuery("select order_no from raw_material_orders");
       
       int order_no = Integer.parseInt(jTextField5.getText());
       
       int flag1 = 0;
        
        while(rs1.next()){
            if(order_no == rs1.getInt("order_no")){
              flag1 = 1;
              break;
            }                
        }
       
       
       while(rd.next()){
            if(supplierid == rd.getInt("id")){
                flag = 1;
                break;
            }
       }
       
       
       if(flag1 == 0){
       
           if(flag == 1){
         
              flag = 0;
              SimpleDateFormat formater = new SimpleDateFormat("yyyy/MM/dd");
        String spinnerValue = formater.format(jSpinner1.getValue());
           
        String s2 = "Insert into raw_material_orders values (?,?,?,?,?)";
       
        PreparedStatement dml_stmt = con1.prepareStatement(s2);
        dml_stmt.setInt(1,orderno);
        dml_stmt.setInt(2,supplierid);
        dml_stmt.setString(3,spinnerValue);
        dml_stmt.setFloat(4,total);
        dml_stmt.setString(5,s);
        dml_stmt.executeUpdate();
        
        
        s2 = "Insert into order_item values (?,?,?)";
        dml_stmt = con1.prepareStatement(s2);
        dml_stmt.setInt(1,orderno);
        dml_stmt.setInt(2,101);
        dml_stmt.setInt(3,qty1);
        dml_stmt.executeUpdate();
        
        dml_stmt.setInt(1,orderno);
        dml_stmt.setInt(2,102);
        dml_stmt.setInt(3,qty2);
        dml_stmt.executeUpdate();
        
        dml_stmt.setInt(1,orderno);
        dml_stmt.setInt(2,103);
        dml_stmt.setInt(3,qty3);
        dml_stmt.executeUpdate();
        
        dml_stmt.setInt(1,orderno);
        dml_stmt.setInt(2,104);
        dml_stmt.setInt(3,qty4);
        dml_stmt.executeUpdate();
        
        
        if(s == "Delivered"){
        Statement stmt=con1.createStatement();
        ResultSet rs=stmt.executeQuery("select qty_available from raw_material where item_no = 101");
        rs.next();
        qty1 += rs.getInt("qty_available");
        
        rs=stmt.executeQuery("select qty_available from raw_material where item_no = 102");
        rs.next();
        qty2 += rs.getInt("qty_available");
        
        rs=stmt.executeQuery("select qty_available from raw_material where item_no = 103");
        rs.next();
        qty3 += rs.getInt("qty_available");
        
        rs=stmt.executeQuery("select qty_available from raw_material where item_no = 104");
        rs.next();
        qty4 += rs.getInt("qty_available");
       
      
        
        String s1 = "update raw_material set qty_available = ? where item_no = 101";
        dml_stmt = con1.prepareStatement(s1);
        dml_stmt.setInt(1,qty1);
        dml_stmt.executeUpdate();
       
        
        s1 = "update raw_material set qty_available = ? where item_no = 102";
        dml_stmt = con1.prepareStatement(s1);
        dml_stmt.setInt(1,qty2);
        dml_stmt.executeUpdate();
        
        
        s1 = "update raw_material set qty_available = ? where item_no = 103";
        dml_stmt = con1.prepareStatement(s1);
        dml_stmt.setInt(1,qty3);
        dml_stmt.executeUpdate();
        
        
        s1 = "update raw_material set qty_available = ? where item_no = 104";
        dml_stmt = con1.prepareStatement(s1);
        dml_stmt.setInt(1,qty4);
        dml_stmt.executeUpdate();
        }
        
        
        
        qty1 = qty2 = qty3 = qty4 =0;
        jTextField1.setText("00");
        jTextField2.setText("00");
        jTextField3.setText("00");
        jTextField4.setText("00");
        jTextField8.setText("00.0");
        jTextField5.setText("00");
        jTextField6.setText("00");
        
        JOptionPane.showMessageDialog(null,"Entries saved successfully");
       }
       else
           JOptionPane.showMessageDialog(null,"No such supplier exists");
       }
       
       else
       {
           if(flag == 1)
           {
               flag = 0;
               
               String s2 = "Update order_item set qty_ordered = ? where order_no = ? and item_no = ?";
               PreparedStatement dml_stmt = con1.prepareStatement(s2);
               dml_stmt = con1.prepareStatement(s2);
               
               dml_stmt.setInt(2,orderno);
               dml_stmt.setInt(3,101);
               dml_stmt.setInt(1,qty1);
               dml_stmt.executeUpdate();
        
               dml_stmt.setInt(2,orderno);
               dml_stmt.setInt(3,102);
               dml_stmt.setInt(1,qty2);
               dml_stmt.executeUpdate();
        
               dml_stmt.setInt(2,orderno);
               dml_stmt.setInt(3,103);
               dml_stmt.setInt(1,qty3);
               dml_stmt.executeUpdate();
        
               dml_stmt.setInt(2,orderno);
               dml_stmt.setInt(3,104);
               dml_stmt.setInt(1,qty4);
               dml_stmt.executeUpdate();
               
               
               
               
               
               
               s2 = "Update raw_material_orders set id = ?,amount_due = ?,status = ? where order_no = ?";
       
               dml_stmt = con1.prepareStatement(s2);
               dml_stmt.setInt(1,supplierid);
               //dml_stmt.setString(3,spinnerValue);
               dml_stmt.setFloat(2,total);
               dml_stmt.setString(3,s);
               dml_stmt.setInt(4,orderno);
               dml_stmt.executeUpdate();
               
               
               
               
               
               
               if(s == "Delivered")
               {
                    Statement stmt=con1.createStatement();
                    
                    
                    ResultSet rs=stmt.executeQuery("select qty_available from raw_material where item_no = 101");
                    rs.next();
                    qty1 += rs.getInt("qty_available");
        
                    rs=stmt.executeQuery("select qty_available from raw_material where item_no = 102");
                    rs.next();
                    qty2 += rs.getInt("qty_available");
        
                    rs=stmt.executeQuery("select qty_available from raw_material where item_no = 103");
                    rs.next();
                    qty3 += rs.getInt("qty_available");
        
                    rs=stmt.executeQuery("select qty_available from raw_material where item_no = 104");
                    rs.next();
                    qty4 += rs.getInt("qty_available");
       
      
        
                    String s1 = "update raw_material set qty_available = ? where item_no = 101";
                    dml_stmt = con1.prepareStatement(s1);
                    dml_stmt.setInt(1,qty1);
                    dml_stmt.executeUpdate();
        
        
                    s1 = "update raw_material set qty_available = ? where item_no = 102";
                    dml_stmt = con1.prepareStatement(s1);
                    dml_stmt.setInt(1,qty2);
                    dml_stmt.executeUpdate();
        
        
                    s1 = "update raw_material set qty_available = ? where item_no = 103";
                    dml_stmt = con1.prepareStatement(s1);
                    dml_stmt.setInt(1,qty3);
                    dml_stmt.executeUpdate();
        
        
                    s1 = "update raw_material set qty_available = ? where item_no = 104";
                    dml_stmt = con1.prepareStatement(s1);
                    dml_stmt.setInt(1,qty4);
                    dml_stmt.executeUpdate();
                
                }
               
               
                    qty1 = qty2 = qty3 = qty4 =0;
                    jTextField1.setText("00");
                    jTextField2.setText("00");
                    jTextField3.setText("00");
                    jTextField4.setText("00");
                    jTextField8.setText("00.0");
                    jTextField5.setText("00");
                    jTextField6.setText("00");
                    
                    JOptionPane.showMessageDialog(null, "Entry Updated successfully");
           }
           
           else
           {
               JOptionPane.showMessageDialog(null,"No such supplier exist with given ID");
           }
       }
       
        
        }catch(Exception e){JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jButton1MouseClicked
    
     
    
    
    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con=DriverManager.getConnection ("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","iit");
        int qty = Integer.parseInt(jTextField1.getText()) - qty1;
        qty1 = Integer.parseInt(jTextField1.getText());
        Statement stmt1=con.createStatement();
        ResultSet rs1=stmt1.executeQuery("select cost from raw_material where item_no = 101");
        rs1.next();
        total = Float.parseFloat(jTextField8.getText());
        total += qty*rs1.getInt("cost");
        String s1 = Float.toString(total);
        jTextField8.setText(s1);
        }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
        try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con=DriverManager.getConnection ("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","iit");
        int qty = Integer.parseInt(jTextField2.getText()) - qty2;
        qty2=Integer.parseInt(jTextField2.getText());
        Statement stmt1=con.createStatement();
        ResultSet rs1=stmt1.executeQuery("select cost from raw_material where item_no = 102");
        rs1.next();
        total = Float.parseFloat(jTextField8.getText());
        total += qty*rs1.getInt("cost");
        String s1 = Float.toString(total);
        jTextField8.setText(s1);
        }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
        try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con=DriverManager.getConnection ("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","iit");
        int qty = Integer.parseInt(jTextField3.getText()) - qty3;
        qty3 = Integer.parseInt(jTextField3.getText());
        Statement stmt1=con.createStatement();
        ResultSet rs1=stmt1.executeQuery("select cost from raw_material where item_no = 103");
        rs1.next();
        total = Float.parseFloat(jTextField8.getText());
        total += qty*rs1.getInt("cost");
        String s1 = Float.toString(total);
        jTextField8.setText(s1);
        }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        // TODO add your handling code here:
        try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con=DriverManager.getConnection ("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","iit");
        int qty = Integer.parseInt(jTextField4.getText()) - qty4;
        qty4=Integer.parseInt(jTextField4.getText());
        Statement stmt1=con.createStatement();
        ResultSet rs1=stmt1.executeQuery("select cost from raw_material where item_no = 104");
        rs1.next();
        total = Float.parseFloat(jTextField8.getText());
        total += qty*rs1.getInt("cost");
        String s1 = Float.toString(total);
        jTextField8.setText(s1);
        }catch(Exception e){System.out.println(e);}
        
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        jButton1.setEnabled(true);
        
        try{
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con=DriverManager.getConnection ("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","iit");
     
        Statement stmt1=con.createStatement();
        ResultSet rs1=stmt1.executeQuery("select order_no from raw_material_orders");
        
        
        int order_no = Integer.parseInt(jTextField5.getText());
        
        int flag1 = 0;
        
        while(rs1.next()){
            if(order_no == rs1.getInt("order_no")){
              flag1 = 1;
              break;
            }                
        }
       
        
        if(flag1 == 1)
        {
            flag1 = 0;
            rs1=stmt1.executeQuery("select * from raw_material_orders where order_no = "+order_no);
            rs1.next();
            jTextField8.setText(Float.toString(rs1.getFloat("amount_due")));
            jTextField6.setText(Integer.toString(rs1.getInt("id")));
            
            
            /*String d = rs1.getString("date_of_order");
            Date date = new SimpleDateFormat("yyyy-mm-dd").parse(d);
            jSpinner1.setValue(date);
            */
                    
            ResultSet rs2 = stmt1.executeQuery("select qty_ordered,item_no from order_item where item_no = 101 and order_no = "+order_no);
            rs2.next();
            jTextField1.setText(Integer.toString(rs2.getInt("qty_ordered")));
            qty1 = rs2.getInt("qty_ordered");
            rs2 = stmt1.executeQuery("select qty_ordered,item_no from order_item where item_no = 102 and order_no = "+order_no);
            rs2.next();
            jTextField2.setText(Integer.toString(rs2.getInt("qty_ordered")));
            qty2 = rs2.getInt("qty_ordered");
            rs2 = stmt1.executeQuery("select qty_ordered,item_no from order_item where item_no = 103 and order_no = "+order_no);
            rs2.next();
            jTextField3.setText(Integer.toString(rs2.getInt("qty_ordered")));
            qty3 = rs2.getInt("qty_ordered");
            rs2 = stmt1.executeQuery("select qty_ordered,item_no from order_item where item_no = 104 and order_no = "+order_no);
            rs2.next();
            jTextField4.setText(Integer.toString(rs2.getInt("qty_ordered")));
            qty4 = rs2.getInt("qty_ordered");
            
            jButton1.setText("UPDATE");
            
            rs2 = stmt1.executeQuery("select status from raw_material_orders where order_no = "+order_no);
            rs2.next();
            
            jRadioButton2.setSelected(true);
            
            if(new String(rs2.getString("status")).equals("Delivered"))
            {
                jRadioButton1.setSelected(true);
                jButton1.setEnabled(false);
                JOptionPane.showMessageDialog(null,"Order already delivered!!");
            }
            
      }
            
      else
      {
                    jTextField1.setText("00");
                    qty1 = 0;
                    jTextField2.setText("00");
                    qty2 = 0;
                    jTextField3.setText("00");
                    qty3 = 0;
                    jTextField4.setText("00");
                    qty4 = 0;
                    jTextField8.setText("00.0");
                    jTextField6.setText("00");
                    jButton1.setText("SUBMIT");
                    
     }
            
        
 }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jTextField5FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertRawMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertRawMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertRawMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertRawMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertRawMaterial().setVisible(true);
           }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
    



}
